<?php
/**
 * 导航栏
 */
    $menu=[
      'manager'=>[
        'manager'=>'管理员管理',
        'manager_url'=>'',
        'manager_child'=>[
            [
                'manager_list'=>'管理员列表',
                'manager_list_url'=>'',
            ],
            [
                'manager_add'=>'添加管理员',
                'manager_add_url'=>'',
            ],
        ]
      ],
      'user'=>[
          'user'=>'用户管理',
          'user_url'=>'',
          'user_child'=>[
              [
                  'user_list'=>'管理员列表',
                  'user_list_url'=>'',
              ],
              [
                  'user_add'=>'添加管理员',
                  'user_add_url'=>'',
              ],
          ]
      ],
      'keywords'=>[
          'keywords'=>'关键词管理',
          'keywords_url'=>'',
          'keywords_child'=>[
              [
                  'keywords_list'=>'管理员列表',
                  'keywords_list_url'=>'',
              ],
              [
                  'keywords_add'=>'添加管理员',
                  'keywords_add_url'=>'',
              ],
          ]
      ]
    ];